### ISSUE TITLE
onessl "Killed: 9"

### ISSUE THREAD

**Issue by fragtom** [kubepack/onessl#9]
Did not work. Downloaded for mac (Darwin) and calling that, resulted with Killed: 9.

```
$ ./onessl create ca-cert
Killed: 9
```

**Comment by tamalsaha** [comment]
This should be fixed now.

Go compiler by default produces large binaries. So, I used [upx](https://upx.github.io/) . But I was using upx 3.91 which produced bad binaries for OSX. https://github.com/upx/upx/issues/4

Now, I have updated upx to 3/94 and rebuilt and pushed the binaries for 0.1.0 release. I have tested in Mac laptop. This is working for me. Please reopen if you are still having this issue.

**Comment by hbokh** [comment]
@tamalsaha Still happens with version 0.12.0:

```
./onessl-darwin-amd64
[1]    77123 killed     ./onessl-darwin-amd64
```

However version 0.10.0 works.

**Comment by tamalsaha** [comment]
I used upx again for the latest 0.12.0 release. I think am going to avoid upx. Thanks for letting me know.

**Comment by tamalsaha** [comment]
@hbokh , it is fixed now. I did not compress darwin binary using upx. Thanks again!

**Comment by tamalsaha** [comment]
Looks like this is a known issue. https://github.com/upx/upx/issues/222
